[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "flask>=3.1.0",
    "pillow>=11.2.1",
    "requests>=2.32.3",
]
